currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 1
subnavBehaviour: null
type: craft
url: entries
