currLabel: Fields
customIcon: null
enabled: true
handle: fields
icon: title
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 1
newWindow: false
parent: null
prevLabel: Fields
prevLevel: null
prevParent: null
prevUrl: /admin/settings/fields
sortOrder: 6
subnavBehaviour: null
type: manual
url: /admin/settings/fields
