currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: '@appicons/graphql.svg'
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 8
subnavBehaviour: null
type: craft
url: graphql
