currLabel: GraphiQL
customIcon: null
enabled: true
handle: graphiql
icon: null
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 2
newWindow: true
parent: a8aef955-3925-412d-b2a5-cc7215467287
prevLabel: GraphiQL
prevLevel: 2
prevParent: a8aef955-3925-412d-b2a5-cc7215467287
prevUrl: graphiql
sortOrder: 11
subnavBehaviour: null
type: craft
url: graphiql
