currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 4
subnavBehaviour: null
type: craft
url: settings
