currLabel: Tokens
customIcon: null
enabled: true
handle: tokens
icon: null
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 2
newWindow: false
parent: a8aef955-3925-412d-b2a5-cc7215467287
prevLabel: Tokens
prevLevel: 2
prevParent: a8aef955-3925-412d-b2a5-cc7215467287
prevUrl: graphql/tokens
sortOrder: 10
subnavBehaviour: null
type: craft
url: graphql/tokens
