currLabel: Users
customIcon: null
enabled: true
handle: users
icon: users
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 1
newWindow: false
parent: null
prevLabel: Users
prevLevel: 1
prevParent: null
prevUrl: users
sortOrder: 7
subnavBehaviour: null
type: craft
url: users
