currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: c26baf0a-9602-427e-a5f6-1c609d7cf009 # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 3
subnavBehaviour: null
type: craft
url: utilities
